import { useEffect, useState } from 'react'
import { AnimatePresence, MotionConfig, motion, useReducedMotion } from 'motion/react'
import { ArrowDown, ArrowLeft, ArrowRight, Bell, BriefcaseBusiness, CarFront, Check, ChevronRight, Clock3, CreditCard, Headphones, Heart, Home, LocateFixed, LockKeyhole, MapPin, MessageCircle, Navigation2, Phone, Plus, Radar, Route, Search, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, Star, UserRound, Wallet, X } from 'lucide-react'
import { AppButton, Avatar, IconButton, Modal, PageHeader, Skeleton, Spinner, SuccessMark, Toast, spring } from './components/ui'
import { TaxiMap } from './components/TaxiMap'
import { drivers, money, places, rideOptions } from './mocks/data'
import { mockTaxiApi } from './services/mockTaxiApi'
import { registerTaxiTools } from './services/webmcp'
import { useTaxiStore } from './store/useTaxiStore'
import type { PaymentMethod, Place, RideStage, Tab, Trip } from './types'
import './styles.css'
import './screens.css'
import './map.css'

type Overlay = 'none' | 'search' | 'pickup' | 'payment' | 'card' | 'saved' | 'settings' | 'developer' | 'detail' | 'personal' | 'language' | 'about'
const tabItems: { id: Tab; label: string; icon: typeof Home }[] = [
  { id: 'home', label: 'Главная', icon: Home }, { id: 'trips', label: 'Поездки', icon: Clock3 },
  { id: 'notifications', label: 'Уведомления', icon: Bell }, { id: 'profile', label: 'Профиль', icon: UserRound },
]
const slides = [
  { eyebrow: 'ДОБРО ПОЖАЛОВАТЬ В VOYA', title: 'Город ближе,\nчем кажется', description: 'Комфортные поездки по Баку — просто, спокойно и в вашем ритме.' },
  { eyebrow: 'ВСЕГДА РЯДОМ', title: 'Водитель уже\nпоблизости', description: 'Выбирайте маршрут и наблюдайте за приближением машины в реальном времени.' },
  { eyebrow: 'ВАШ ВЫБОР', title: 'Поездка под\nваши правила', description: 'Подберите тариф, удобную оплату и детали, которые важны именно вам.' },
]

function Logo({ light = false }: { light?: boolean }) { return <div className={`wordmark ${light ? 'light' : ''}`}><span className="logo-dot" />voya<span className="logo-period">.</span></div> }

function Onboarding({ onDone }: { onDone: () => void }) {
  const [index, setIndex] = useState(0)
  const slide = slides[index]
  return <div className="intro-screen" onTouchStart={e => { (e.currentTarget as HTMLElement).dataset.x = String(e.touches[0].clientX) }} onTouchEnd={e => { const x = Number((e.currentTarget as HTMLElement).dataset.x); const dx = e.changedTouches[0].clientX - x; if (Math.abs(dx) > 60) setIndex(i => Math.max(0, Math.min(2, i + (dx < 0 ? 1 : -1)))) }}>
    <div className="intro-top"><Logo /><button onClick={onDone} className="skip-button">Пропустить</button></div>
    <AnimatePresence mode="wait"><motion.div key={index} className="intro-content" initial={{ opacity: 0, x: 38 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -38 }} transition={spring}>
      <div className={`intro-art art-${index}`}><img src="/onboarding-car.png" alt="Иллюстрация автомобиля на улице Баку" /><div className="art-caption"><Navigation2 size={15} fill="currentColor" /> Баку, Азербайджан</div></div>
      <p className="eyebrow">{slide.eyebrow}</p><h1>{slide.title.split('\n').map((part, i) => <span key={part}>{part}{i === 0 && <br />}</span>)}</h1><p className="intro-description">{slide.description}</p>
    </motion.div></AnimatePresence>
    <div className="intro-bottom"><div className="page-dots">{slides.map((_, i) => <button key={i} onClick={() => setIndex(i)} aria-label={`Экран ${i + 1}`} className={i === index ? 'active' : ''} />)}</div><AppButton onClick={() => index === 2 ? onDone() : setIndex(index + 1)}>{index === 2 ? 'Начать' : 'Продолжить'}<ArrowRight size={19} /></AppButton></div>
  </div>
}

function Auth({ onComplete }: { onComplete: () => void }) {
  const set = useTaxiStore(s => s.set)
  const [step, setStep] = useState<'welcome' | 'phone' | 'otp' | 'name'>('welcome')
  const [country, setCountry] = useState('+994')
  const [showCountries, setShowCountries] = useState(false)
  const [phone, setPhone] = useState('')
  const [otp, setOtp] = useState('')
  const [firstName, setFirstName] = useState('')
  const [lastName, setLastName] = useState('')
  const [email, setEmail] = useState('')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const nextPhone = async () => { if (phone.replace(/\D/g, '').length < 8) { setError('Введите корректный номер телефона'); return } setBusy(true); await mockTaxiApi.login(`${country} ${phone}`); setBusy(false); setError(''); setStep('otp') }
  const verify = async () => { setBusy(true); const ok = await mockTaxiApi.verifyOtp(otp); setBusy(false); if (ok) { setError(''); setStep('name') } else setError('Введите любой 6-значный код') }
  const finish = () => { if (!firstName.trim() || !lastName.trim()) { setError('Укажите имя и фамилию'); return } set({ user: { firstName: firstName.trim(), lastName: lastName.trim(), phone: `${country} ${phone}`, email: email.trim() || undefined } }); onComplete() }
  const apple = async () => { setBusy(true); const user = await mockTaxiApi.loginWithApple(); set({ user }); setBusy(false); onComplete() }
  return <div className="auth-screen"><div className="auth-top"><Logo /><div className="auth-orb"><CarFront size={72} strokeWidth={1.1} /><span className="orb-pin"><MapPin size={18} fill="currentColor" /></span></div></div>
    <AnimatePresence mode="wait"><motion.div key={step} className="auth-body" initial={{ opacity: 0, x: 28 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -24 }} transition={spring}>
      {step === 'welcome' && <><p className="eyebrow">ПУТЬ НАЧИНАЕТСЯ ЗДЕСЬ</p><h1>Рады видеть вас в Voya</h1><p className="muted">Ваш город. Ваш маршрут. Ваше время.</p><div className="auth-actions"><AppButton onClick={() => setStep('phone')} icon={Phone}>Продолжить по номеру</AppButton><AppButton onClick={apple} variant="secondary" disabled={busy}>{busy ? <Spinner /> : <span className="apple-symbol">●</span>} Продолжить с Apple</AppButton></div></>}
      {step === 'phone' && <><button className="back-inline" onClick={() => setStep('welcome')}><ArrowLeft size={20} /> Назад</button><p className="eyebrow">ВАШ НОМЕР</p><h1>Давайте знакомиться</h1><p className="muted">Отправим код подтверждения. Для демо подойдёт любой номер.</p><div className="phone-field"><button onClick={() => setShowCountries(v => !v)}>{country} <ChevronRight size={17} /></button><input autoFocus inputMode="tel" placeholder="50 123 45 67" value={phone} onChange={e => setPhone(e.target.value)} aria-label="Номер телефона" /></div>{showCountries && <div className="country-list">{[['Азербайджан', '+994'], ['Турция', '+90'], ['Грузия', '+995']].map(([name, code]) => <button key={code} onClick={() => { setCountry(code); setShowCountries(false) }}>{name}<span>{code}</span></button>)}</div>}<p className="field-error">{error}</p><AppButton onClick={nextPhone} disabled={busy}>{busy ? <Spinner /> : 'Получить код'}</AppButton></>}
      {step === 'otp' && <><button className="back-inline" onClick={() => setStep('phone')}><ArrowLeft size={20} /> Назад</button><p className="eyebrow">ПОДТВЕРЖДЕНИЕ</p><h1>Введите код</h1><p className="muted">Мы отправили код на {country} {phone}. В демо подойдёт любой 6-значный код.</p><input autoFocus className="otp-input" inputMode="numeric" maxLength={6} placeholder="000000" value={otp} onChange={e => setOtp(e.target.value.replace(/\D/g, ''))} aria-label="Шестизначный код" /><p className="field-error">{error}</p><AppButton onClick={verify} disabled={busy || otp.length !== 6}>{busy ? <Spinner /> : 'Подтвердить'}</AppButton></>}
      {step === 'name' && <><p className="eyebrow">ПОЧТИ ГОТОВО</p><h1>Как к вам обращаться?</h1><p className="muted">Имя увидит водитель перед поездкой.</p><div className="form-stack"><input autoFocus placeholder="Имя" value={firstName} onChange={e => setFirstName(e.target.value)} aria-label="Имя" /><input placeholder="Фамилия" value={lastName} onChange={e => setLastName(e.target.value)} aria-label="Фамилия" /><input type="email" placeholder="Email (необязательно)" value={email} onChange={e => setEmail(e.target.value)} aria-label="Email" /></div><p className="field-error">{error}</p><AppButton onClick={finish}>Поехали</AppButton></>}
    </motion.div></AnimatePresence><p className="auth-legal">Продолжая, вы соглашаетесь с условиями тестовой версии.</p></div>
}

function AddressRow({ place, onClick, icon: Icon = MapPin, trailing }: { place: Place; onClick: () => void; icon?: typeof MapPin; trailing?: string }) { return <motion.button whileTap={{ scale: .985 }} className="address-row" onClick={onClick}><span className="address-icon"><Icon size={20} /></span><span className="address-copy"><strong>{place.name}</strong><small>{place.address}</small></span><span className="address-distance">{trailing ?? place.distance}</span></motion.button> }

function SearchScreen({ mode, onBack, onSelect }: { mode: 'pickup' | 'destination'; onBack: () => void; onSelect: (place: Place) => void }) {
  const [query, setQuery] = useState('')
  const [results, setResults] = useState<Place[]>(places.slice(1))
  const [busy, setBusy] = useState(false)
  const saved = useTaxiStore(s => s.saved)
  useEffect(() => { let live = true; setBusy(true); const t = setTimeout(() => { mockTaxiApi.searchPlaces(query).then(v => { if (live) { setResults(v); setBusy(false) } }) }, 140); return () => { live = false; clearTimeout(t) } }, [query])
  return <div className="full-screen search-screen"><PageHeader title={mode === 'pickup' ? 'Точка отправления' : 'Куда едем?'} onBack={onBack} /><div className="screen-content"><div className="search-field"><Search size={21} /><input autoFocus placeholder={mode === 'pickup' ? 'Откуда поедем?' : 'Адрес или название места'} value={query} onChange={e => setQuery(e.target.value)} aria-label="Поиск адреса" />{query && <button onClick={() => setQuery('')} aria-label="Очистить"><X size={17} /></button>}</div>
    {mode === 'pickup' && <div className="result-group"><p className="section-kicker">БЫСТРЫЙ ВЫБОР</p><AddressRow place={places[0]} icon={LocateFixed} onClick={() => onSelect(places[0])} />{saved.home && <AddressRow place={saved.home} icon={Home} onClick={() => onSelect(saved.home!)} />}{saved.work && <AddressRow place={saved.work} icon={BriefcaseBusiness} onClick={() => onSelect(saved.work!)} />}</div>}
    <div className="result-group"><p className="section-kicker">{query ? 'РЕЗУЛЬТАТЫ ПОИСКА' : 'ПОПУЛЯРНОЕ РЯДОМ'}</p>{busy ? <div className="result-skeletons"><Skeleton /><Skeleton /><Skeleton /></div> : results.length ? results.map(place => <AddressRow key={place.id} place={place} onClick={() => onSelect(place)} />) : <div className="empty-inline"><Search size={25} /><strong>Ничего не найдено</strong><span>Попробуйте другое название места</span></div>}</div></div></div>
}

function DriverCard({ onToast }: { onToast: (s: string) => void }) {
  const driver = useTaxiStore(s => s.driver)
  if (!driver) return null
  return <div className="driver-card"><Avatar initials={driver.initials} large /><div className="driver-main"><strong>{driver.name}</strong><span><Star size={14} fill="currentColor" /> {driver.rating} · {driver.car}</span><small>{driver.color} · <b>{driver.plate}</b></small></div><div className="driver-actions"><IconButton icon={Phone} label="Позвонить водителю" onClick={() => onToast('Звонок доступен в полной версии')} /><IconButton icon={MessageCircle} label="Написать водителю" onClick={() => onToast('Чат доступен в полной версии')} /></div></div>
}

function TabBar({ active, onChange, unread }: { active: Tab; onChange: (tab: Tab) => void; unread: boolean }) { return <nav className="tab-bar" aria-label="Основная навигация">{tabItems.map(item => <button key={item.id} className={active === item.id ? 'active' : ''} onClick={() => onChange(item.id)} aria-current={active === item.id ? 'page' : undefined}><span className="tab-icon"><item.icon size={21} strokeWidth={active === item.id ? 2.4 : 1.9} />{item.id === 'notifications' && unread && <span className="unread-dot" />}{active === item.id && <motion.span layoutId="tabGlow" className="tab-glow" transition={spring} />}</span><small>{item.label}</small></button>)}</nav> }

function HomeSheet({ openSearch, openPickup, openPayment, toast, setToast }: { openSearch: () => void; openPickup: () => void; openPayment: () => void; toast: (s: string) => void; setToast: (s: string) => void }) {
  const { stage, pickup, destination, rideOptionId, payment, cardLast4, eta, progress, options, comment, set, resetRide } = useTaxiStore()
  const [size, setSize] = useState<'collapsed' | 'medium' | 'expanded'>('medium')
  const [showOptions, setShowOptions] = useState(false)
  const [showComment, setShowComment] = useState(false)
  const [safety, setSafety] = useState(false)
  const selected = rideOptions.find(o => o.id === rideOptionId) ?? rideOptions[0]
  const paymentLabel = payment === 'apple' ? 'Apple Pay' : payment === 'card' ? `Карта •••• ${cardLast4 ?? '4242'}` : 'Наличные'
  const request = async () => { set({ stage: 'searchingDriver', progress: 0 }); const trip = await mockTaxiApi.requestRide(); set({ tripId: trip.id }) }
  const start = async () => { set({ stage: 'rideStarted', progress: 0 }); await mockTaxiApi.startRide(); set({ stage: 'inProgress' }) }
  const selectedOption = (id: string) => set({ rideOptionId: id })
  const stageIsIdle = ['idle','cancelled','selectingPickup','selectingDestination'].includes(stage)
  return <><motion.div className={`home-sheet sheet-${stageIsIdle ? size : 'ride'}`} drag={stageIsIdle ? 'y' : false} dragConstraints={{ top: 0, bottom: 0 }} dragElastic={.18} onDragEnd={(_, info) => { if (info.offset.y < -65) setSize('expanded'); else if (info.offset.y > 95) setSize('collapsed'); else setSize('medium') }} layout transition={spring}>
    <div className="sheet-handle" onClick={() => setSize(size === 'expanded' ? 'medium' : 'expanded')} role="button" tabIndex={0} onKeyDown={e => e.key === 'Enter' && setSize(size === 'expanded' ? 'medium' : 'expanded')} aria-label="Изменить размер панели"><span /></div>
    {stageIsIdle && <div className="sheet-inner home-entry"><div className="sheet-heading"><div><p className="eyebrow">ВАША ПОЕЗДКА</p><h2>Куда едем?</h2></div><span className="heading-icon"><Sparkles size={18} /></span></div><button className="destination-cta" onClick={openSearch}><Search size={22} /><span>Адрес или название места</span><ArrowRight size={19} /></button><div className="quick-places"><button onClick={openPickup}><span className="quick-icon"><LocateFixed size={19} /></span><span><strong>Откуда</strong><small>{pickup.name}</small></span><ChevronRight size={18} /></button><button onClick={() => { const p = useTaxiStore.getState().saved.home; if (p) set({ destination: p, stage: 'routePreview' }); else toast('Добавьте адрес дома в профиле') }}><span className="quick-icon"><Home size={19} /></span><span><strong>Дом</strong><small>{useTaxiStore.getState().saved.home?.name ?? 'Добавить адрес'}</small></span><ChevronRight size={18} /></button></div>{size === 'expanded' && <div className="recent-places"><p className="section-kicker">ПОПУЛЯРНЫЕ МЕСТА</p>{places.slice(2, 5).map(p => <AddressRow key={p.id} place={p} onClick={() => set({ destination: p, stage: 'routePreview' })} />)}</div>}</div>}
    {stage === 'routePreview' && destination && <div className="sheet-inner"><p className="eyebrow">МАРШРУТ ГОТОВ</p><h2>{destination.name}</h2><div className="route-addresses"><div><span className="route-dot from" /><span><small>Откуда</small><strong>{pickup.name}</strong></span><button onClick={openPickup} aria-label="Изменить точку отправления"><ChevronRight size={19} /></button></div><div><span className="route-dot to" /><span><small>Куда</small><strong>{destination.name}</strong></span><button onClick={openSearch} aria-label="Изменить пункт назначения"><ChevronRight size={19} /></button></div></div><div className="route-stats"><span><Clock3 size={18} /> 12 мин</span><span><Route size={18} /> 5.8 км</span></div><AppButton onClick={async () => { set({ stage: 'selectingRide' }); await mockTaxiApi.getRideOptions() }}>Выбрать тариф <ArrowRight size={19} /></AppButton><button className="subtle-link" onClick={resetRide}>Отменить маршрут</button></div>}
    {stage === 'selectingRide' && destination && <div className="sheet-inner"><div className="sheet-heading"><div><p className="eyebrow">ВАШ МАРШРУТ · 12 МИН</p><h2>Выберите поездку</h2></div><button className="small-edit" onClick={() => set({ stage: 'routePreview' })}>Изменить</button></div><div className="ride-list">{rideOptions.map(option => <motion.button key={option.id} whileTap={{ scale: .985 }} className={`ride-option ${rideOptionId === option.id ? 'selected' : ''}`} onClick={() => selectedOption(option.id)}>{rideOptionId === option.id && <motion.span layoutId="rideOptionSelection" className="ride-option-bg" transition={spring} />}<span className={`ride-car ${option.kind}`}><img src={option.kind === 'premium' || option.kind === 'xl' ? '/suv.png' : '/sedan.png'} alt="" /></span><span className="ride-copy"><strong>{option.name}</strong><small>{option.eta} мин · {option.seats} места</small></span><strong className="ride-price">{money(option.price)}</strong></motion.button>)}</div><button className="payment-inline" onClick={openPayment}><span className="payment-mini-icon"><Wallet size={20} /></span><span>{paymentLabel}</span><ChevronRight size={19} /></button><AppButton onClick={() => set({ stage: 'confirming' })}>Продолжить <ArrowRight size={19} /></AppButton></div>}
    {stage === 'confirming' && destination && <div className="sheet-inner"><p className="eyebrow">ПОЧТИ ГОТОВО</p><h2>Проверьте детали</h2><div className="confirm-route"><span>{pickup.name}</span><ArrowDown size={17} /><strong>{destination.name}</strong></div><div className="confirm-sum"><span>{selected.name} · {selected.eta} мин</span><strong>{money(selected.price)}</strong></div><button className="payment-inline" onClick={openPayment}><Wallet size={20} /><span>{paymentLabel}</span><ChevronRight size={19} /></button><button className="extra-toggle" onClick={() => setShowOptions(v => !v)}><SlidersHorizontal size={19} /> Дополнительные пожелания <ChevronRight size={18} className={showOptions ? 'rotated' : ''} /></button>{showOptions && <div className="extra-options">{['Позвоните, когда приедете', 'Детское кресло', 'Тихая поездка'].map(label => <button key={label} className={options.includes(label) ? 'active' : ''} onClick={() => set({ options: options.includes(label) ? options.filter(x => x !== label) : [...options, label] })}><span>{label}</span><span className="fake-check">{options.includes(label) && <Check size={14} />}</span></button>)}<button onClick={() => setShowComment(v => !v)}><MessageCircle size={17} /> Комментарий водителю</button>{showComment && <textarea value={comment} onChange={e => set({ comment: e.target.value })} placeholder="Например, я у главного входа" aria-label="Комментарий водителю" />}</div>}<AppButton onClick={request}>Заказать {selected.name} · {money(selected.price)}</AppButton><button className="subtle-link" onClick={() => set({ stage: 'selectingRide' })}>Назад к тарифам</button></div>}
    {stage === 'searchingDriver' && <div className="sheet-inner status-sheet"><div className="radar-icon"><Radar size={27} /></div><p className="eyebrow">ИЩЕМ ЛУЧШИЙ ВАРИАНТ</p><h2>Ищем водителя<span className="animated-dots">...</span></h2><p className="muted">Обычно это занимает всего несколько секунд.</p><div className="search-summary"><span>{selected.name}</span><span>{money(selected.price)}</span><span>{paymentLabel}</span></div><AppButton variant="secondary" onClick={() => set({ stage: 'cancelled', driver: null })}>Отменить поиск</AppButton></div>}
    {stage === 'searchError' && <div className="sheet-inner status-sheet"><div className="status-icon error"><X size={27} /></div><h2>Пока нет водителей</h2><p className="muted">Попробуйте ещё раз — машины скоро появятся поблизости.</p><AppButton onClick={request}>Попробовать снова</AppButton><AppButton variant="text" onClick={resetRide}>Вернуться на главную</AppButton></div>}
    {stage === 'driverFound' && <div className="sheet-inner status-sheet"><SuccessMark /><p className="eyebrow">ХОРОШИЕ НОВОСТИ</p><h2>Водитель найден</h2><p className="muted">Он уже направляется к вам.</p><DriverCard onToast={setToast} /></div>}
    {stage === 'driverApproaching' && <div className="sheet-inner"><p className="eyebrow">ВОДИТЕЛЬ ЕДЕТ К ВАМ</p><div className="eta-heading"><h2>{eta} мин</h2><span>до подачи</span></div><div className="progress-track"><motion.span animate={{ width: `${progress * 100}%` }} transition={{ duration: .9 }} /></div><DriverCard onToast={setToast} /><p className="ride-hint">Встречайте машину у точки отправления</p></div>}
    {stage === 'driverArrived' && <div className="sheet-inner"><div className="status-icon arrived"><CarFront size={29} /></div><p className="eyebrow">МОЖНО САДИТЬСЯ</p><h2>Водитель прибыл</h2><p className="muted">{useTaxiStore.getState().driver?.car} ждёт вас · {useTaxiStore.getState().driver?.plate}</p><DriverCard onToast={setToast} /><AppButton onClick={start}>Я в машине <ArrowRight size={19} /></AppButton></div>}
    {['rideStarted','inProgress'].includes(stage) && destination && <div className="sheet-inner"><p className="eyebrow">ПОЕЗДКА ИДЁТ</p><h2>Едем к {destination.name}</h2><div className="active-stats"><div><small>ПРИБУДЕМ ЧЕРЕЗ</small><strong>{Math.max(1, Math.ceil((1 - progress) * 8))} мин</strong></div><div><small>ОСТАЛОСЬ</small><strong>{((1 - progress) * 5.8).toFixed(1)} км</strong></div></div><div className="progress-track"><motion.span animate={{ width: `${progress * 100}%` }} /></div><DriverCard onToast={setToast} /><div className="ride-tools"><button onClick={() => setSafety(true)}><ShieldCheck size={20} />Безопасность</button><button onClick={() => toast('Чат доступен в полной версии')}><MessageCircle size={20} />Связаться</button><button onClick={() => toast('Ссылка на поездку скопирована (демо)')}><Heart size={20} />Поделиться</button></div></div>}
    {stage === 'rideCompleted' && <div className="sheet-inner status-sheet"><SuccessMark /><p className="eyebrow">ПОЕЗДКА ЗАВЕРШЕНА</p><h2>Вы приехали</h2><p className="muted">Спасибо, что поехали с Voya.</p><div className="completion-stats"><div><small>СТОИМОСТЬ</small><strong>{money(selected.price)}</strong></div><div><small>ВРЕМЯ</small><strong>14 мин</strong></div><div><small>ПУТЬ</small><strong>5.8 км</strong></div></div><AppButton onClick={() => payment === 'cash' ? set({ stage: 'rating' }) : set({ stage: 'processingPayment' })}>{payment === 'cash' ? 'Оценить поездку' : 'Оплатить поездку'}</AppButton></div>}
    {stage === 'processingPayment' && <div className="sheet-inner status-sheet"><div className="radar-icon"><Spinner size={31} /></div><h2>Обрабатываем оплату</h2><p className="muted">Это тестовая оплата. Реальные средства не списываются.</p></div>}
    {stage === 'paymentSuccess' && <div className="sheet-inner status-sheet"><SuccessMark /><p className="eyebrow">ГОТОВО</p><h2>Оплата прошла</h2><p className="muted">Средства не списаны — это демонстрационная поездка.</p></div>}
    {stage === 'paymentError' && <div className="sheet-inner status-sheet"><div className="status-icon error"><X size={26} /></div><h2>Ошибка оплаты</h2><p className="muted">Тестовый платёж не прошёл. Попробуйте снова или выберите наличные.</p><AppButton onClick={() => set({ stage: 'processingPayment' })}>Повторить</AppButton><AppButton variant="secondary" onClick={openPayment}>Изменить способ оплаты</AppButton></div>}
    {stage === 'rating' && <Rating onFinish={rating => useTaxiStore.getState().finishTrip(rating)} />}
  </motion.div><Modal open={safety} title="Безопасность" onClose={() => setSafety(false)}><p className="demo-note">Демо-режим: действия ниже не вызывают экстренные службы.</p>{[['Экстренная помощь', ShieldCheck], ['Поделиться поездкой', Heart], ['Связаться с поддержкой', Headphones]].map(([label, Icon]) => { const I = Icon as typeof ShieldCheck; return <button key={label as string} className="menu-row" onClick={() => { setSafety(false); toast('Функция доступна в полной версии') }}><I size={21} /><span>{label as string}</span><ChevronRight size={18} /></button> })}</Modal></>
}

function Rating({ onFinish }: { onFinish: (rating: number) => void }) {
  const [rating, setRating] = useState(0)
  const [tags, setTags] = useState<string[]>([])
  const [comment, setComment] = useState('')
  const [busy, setBusy] = useState(false)
  const submit = async () => { setBusy(true); await mockTaxiApi.submitRating(rating, comment); onFinish(rating) }
  return <div className="sheet-inner rating-sheet"><p className="eyebrow">ВАША ОБРАТНАЯ СВЯЗЬ</p><h2>Как прошла поездка?</h2><p className="muted">Оцените водителя и помогите нам стать лучше.</p><div className="rating-stars">{[1,2,3,4,5].map(n => <motion.button key={n} whileTap={{ scale: .75 }} onClick={() => setRating(n)} aria-label={`${n} звёзд`}><Star size={37} fill={rating >= n ? 'currentColor' : 'none'} strokeWidth={1.5} /></motion.button>)}</div><div className="rating-tags">{['Отличный водитель','Чистый автомобиль','Аккуратное вождение','Вежливый водитель'].map(tag => <button key={tag} className={tags.includes(tag) ? 'active' : ''} onClick={() => setTags(tags.includes(tag) ? tags.filter(x => x !== tag) : [...tags, tag])}>{tag}</button>)}</div><textarea placeholder="Комментарий (необязательно)" value={comment} onChange={e => setComment(e.target.value)} aria-label="Комментарий к поездке" /><AppButton onClick={submit} disabled={busy || !rating}>{busy ? <Spinner /> : 'Отправить оценку'}</AppButton><button className="subtle-link" onClick={() => onFinish(0)}>Пропустить</button></div>
}

function PaymentScreen({ onBack, onCard }: { onBack: () => void; onCard: () => void }) {
  const { payment, cardLast4, set } = useTaxiStore()
  const [confirmApple, setConfirmApple] = useState(false)
  const choose = (method: PaymentMethod) => { if (method === 'apple') setConfirmApple(true); else { set({ payment: method }); onBack() } }
  return <div className="full-screen"><PageHeader title="Способ оплаты" onBack={onBack} /><div className="screen-content"><p className="section-kicker">ВЫБЕРИТЕ УДОБНЫЙ СПОСОБ</p><button className={`payment-row ${payment === 'apple' ? 'selected' : ''}`} onClick={() => choose('apple')}><span className="payment-brand apple">●</span><span><strong>Apple Pay</strong><small>Быстро и удобно</small></span>{payment === 'apple' && <Check size={21} />}</button><button className={`payment-row ${payment === 'card' ? 'selected' : ''}`} onClick={() => cardLast4 ? choose('card') : onCard()}><span className="payment-brand"><CreditCard size={23} /></span><span><strong>Банковская карта</strong><small>{cardLast4 ? `•••• ${cardLast4}` : 'Добавить тестовую карту'}</small></span>{payment === 'card' ? <Check size={21} /> : <ChevronRight size={19} />}</button><button className={`payment-row ${payment === 'cash' ? 'selected' : ''}`} onClick={() => choose('cash')}><span className="payment-brand"><Wallet size={23} /></span><span><strong>Наличные</strong><small>Оплата водителю после поездки</small></span>{payment === 'cash' && <Check size={21} />}</button><p className="demo-note"><LockKeyhole size={17} /> Тестовая оплата. Реальные средства не списываются.</p></div><Modal open={confirmApple} title="Подтвердить Apple Pay" onClose={() => setConfirmApple(false)}><div className="apple-confirm"><span className="apple-large">● Pay</span><p>Использовать Apple Pay для будущей поездки?</p><small>Это демонстрация. Списаний не будет.</small><AppButton onClick={() => { set({ payment: 'apple' }); setConfirmApple(false); onBack() }}>Выбрать Apple Pay</AppButton></div></Modal></div>
}

function CardScreen({ onBack }: { onBack: () => void }) {
  const set = useTaxiStore(s => s.set)
  const [number, setNumber] = useState('')
  const [expiry, setExpiry] = useState('')
  const [cvv, setCvv] = useState('')
  const [holder, setHolder] = useState('')
  const [error, setError] = useState('')
  const save = () => { if (number.replace(/\D/g, '').length < 12 || !expiry || cvv.length < 3 || !holder.trim()) { setError('Заполните все поля тестовой карты'); return } set({ cardLast4: number.replace(/\D/g, '').slice(-4), payment: 'card' }); setNumber(''); setCvv(''); onBack() }
  return <div className="full-screen"><PageHeader title="Добавить карту" onBack={onBack} /><div className="screen-content"><div className="card-preview"><span>voya.</span><CreditCard size={34} /><strong>•••• {number.replace(/\D/g, '').slice(-4) || '4242'}</strong><small>{holder || 'CARDHOLDER'}</small></div><div className="form-stack"><label>Номер карты<input inputMode="numeric" placeholder="0000 0000 0000 0000" maxLength={19} value={number} onChange={e => setNumber(e.target.value.replace(/\D/g, '').replace(/(.{4})/g, '$1 ').trim())} /></label><div className="form-pair"><label>Срок действия<input placeholder="MM/YY" maxLength={5} value={expiry} onChange={e => setExpiry(e.target.value)} /></label><label>CVV<input type="password" inputMode="numeric" placeholder="•••" maxLength={4} value={cvv} onChange={e => setCvv(e.target.value.replace(/\D/g, ''))} /></label></div><label>Имя на карте<input placeholder="FARID ALIYEV" value={holder} onChange={e => setHolder(e.target.value.toUpperCase())} /></label></div><p className="field-error">{error}</p><p className="demo-note"><LockKeyhole size={17} /> Демо-карта. Данные не отправляются. CVV не сохраняется.</p><AppButton onClick={save}>Сохранить карту</AppButton></div></div>
}

function TripsScreen({ onOpen }: { onOpen: (trip: Trip) => void }) {
  const trips = useTaxiStore(s => s.trips)
  const [loading, setLoading] = useState(true)
  useEffect(() => { const t = setTimeout(() => setLoading(false), 500); return () => clearTimeout(t) }, [])
  return <div className="tab-screen"><div className="tab-title"><p className="eyebrow">ВАШИ МАРШРУТЫ</p><h1>Поездки</h1></div>{loading ? <div className="trip-loading"><Skeleton /><Skeleton /><Skeleton /></div> : trips.length ? <div className="trip-list">{trips.map(trip => <motion.button whileTap={{ scale: .98 }} className="trip-card" key={trip.id} onClick={() => onOpen(trip)}><div className="trip-card-top"><span>{new Date(trip.date).toLocaleDateString('ru-RU', { day: 'numeric', month: 'long' })}</span><span className="trip-status"><Check size={13} /> Завершена</span></div><div className="trip-places"><span className="route-dot from" /><strong>{trip.pickup.name}</strong><span className="route-dot to" /><strong>{trip.destination.name}</strong></div><div className="trip-card-bottom"><span>{trip.duration} мин · {trip.distance} км</span><strong>{money(trip.price)}</strong></div></motion.button>)}</div> : <div className="empty-state"><div className="empty-icon"><Route size={32} /></div><h2>Пока нет поездок</h2><p>Когда вы совершите первую поездку, её детали появятся здесь.</p><AppButton onClick={() => useTaxiStore.getState().set({ tab: 'home' })}>Заказать поездку</AppButton></div>}</div>
}

function TripDetail({ trip, onBack, onRepeat }: { trip: Trip; onBack: () => void; onRepeat: () => void }) { return <div className="full-screen"><PageHeader title="Детали поездки" onBack={onBack} /><div className="detail-map"><TaxiMap trip={trip} /></div><div className="screen-content detail-content"><div className="detail-title"><div><p className="eyebrow">ПОЕЗДКА ЗАВЕРШЕНА</p><h2>{trip.destination.name}</h2><small>{new Date(trip.date).toLocaleString('ru-RU', { day: 'numeric', month: 'long', hour: '2-digit', minute: '2-digit' })}</small></div><strong>{money(trip.price)}</strong></div><div className="detail-route route-addresses"><div><span className="route-dot from" /><span><small>Откуда</small><strong>{trip.pickup.name}</strong></span></div><div><span className="route-dot to" /><span><small>Куда</small><strong>{trip.destination.name}</strong></span></div></div><div className="detail-section"><p className="section-kicker">ПОЕЗДКА</p><div className="detail-line"><span>Водитель</span><strong>{trip.driver.name}</strong></div><div className="detail-line"><span>Автомобиль</span><strong>{trip.driver.car}</strong></div><div className="detail-line"><span>Номер</span><strong>{trip.driver.plate}</strong></div><div className="detail-line"><span>Оплата</span><strong>{trip.payment === 'apple' ? 'Apple Pay' : trip.payment === 'card' ? 'Карта' : 'Наличные'}</strong></div></div><div className="detail-section"><p className="section-kicker">СТОИМОСТЬ</p><div className="detail-line"><span>Поездка</span><strong>{money(trip.price - 1.4)}</strong></div><div className="detail-line"><span>Сервисный сбор</span><strong>1.40 ₼</strong></div><div className="detail-line total"><span>Итого</span><strong>{money(trip.price)}</strong></div></div><AppButton onClick={onRepeat}>Повторить поездку</AppButton></div></div> }

function NotificationsScreen() {
  const { notices, set } = useTaxiStore()
  return <div className="tab-screen"><div className="tab-title row-title"><div><p className="eyebrow">ВОЯ В КУРСЕ</p><h1>Уведомления</h1></div>{notices.some(n => n.unread) && <button onClick={() => set({ notices: notices.map(n => ({ ...n, unread: false })) })}>Прочитать все</button>}</div>{notices.length ? <div className="notice-list">{notices.map(n => <button key={n.id} className={`notice-row ${n.unread ? 'unread' : ''}`} onClick={() => set({ notices: notices.map(v => v.id === n.id ? { ...v, unread: false } : v) })}><span className="notice-icon">{n.type === 'ride' ? <CarFront size={21} /> : <Sparkles size={21} />}</span><span><strong>{n.title}</strong><small>{n.body}</small><em>{n.time}</em></span>{n.unread && <i />}</button>)}</div> : <div className="empty-state"><div className="empty-icon"><Bell size={30} /></div><h2>Пока тихо</h2><p>Здесь появятся новости о ваших поездках и предложениях.</p></div>}</div>
}

function ProfileScreen({ go, toast }: { go: (screen: Overlay) => void; toast: (s: string) => void }) {
  const { user, cardLast4, set } = useTaxiStore()
  const initials = `${user?.firstName?.[0] ?? 'V'}${user?.lastName?.[0] ?? ''}`.toUpperCase()
  const sections: { title: string; rows: { label: string; icon: typeof UserRound; action: () => void; value?: string }[] }[] = [
    { title: 'АККАУНТ', rows: [{ label: 'Личные данные', icon: UserRound, action: () => go('personal') }, { label: 'Способы оплаты', icon: CreditCard, action: () => go('payment'), value: cardLast4 ? `•••• ${cardLast4}` : undefined }, { label: 'Сохранённые места', icon: MapPin, action: () => go('saved') }, { label: 'История поездок', icon: Clock3, action: () => set({ tab: 'trips' }) }] },
    { title: 'ПРИЛОЖЕНИЕ', rows: [{ label: 'Уведомления', icon: Bell, action: () => set({ tab: 'notifications' }) }, { label: 'Безопасность', icon: ShieldCheck, action: () => toast('Функции безопасности доступны во время поездки') }, { label: 'Поддержка', icon: Headphones, action: () => toast('Поддержка доступна в полной версии') }, { label: 'Настройки', icon: Settings2, action: () => go('settings') }] },
  ]
  return <div className="tab-screen profile-screen"><div className="tab-title"><p className="eyebrow">ВАШ ПРОФИЛЬ</p><h1>Профиль</h1></div><button className="profile-hero" onClick={() => go('personal')}><Avatar initials={initials} large /><span><strong>{user?.firstName} {user?.lastName}</strong><small>{user?.phone}</small></span><ChevronRight size={20} /></button>{sections.map(section => <div className="profile-section" key={section.title}><p className="section-kicker">{section.title}</p>{section.rows.map(row => <button key={row.label} className="menu-row" onClick={row.action}><row.icon size={20} /><span>{row.label}</span>{row.value && <small>{row.value}</small>}<ChevronRight size={18} /></button>)}</div>)}<Logo /></div>
}

function SavedPlaces({ onBack }: { onBack: () => void }) {
  const { saved, set } = useTaxiStore()
  const [editing, setEditing] = useState<'home' | 'work' | null>(null)
  return <div className="full-screen"><PageHeader title="Сохранённые места" onBack={editing ? () => setEditing(null) : onBack} /><div className="screen-content">{editing ? <><p className="section-kicker">{editing === 'home' ? 'ДОМАШНИЙ АДРЕС' : 'РАБОЧИЙ АДРЕС'}</p><div className="result-group">{places.slice(1).map(p => <AddressRow key={p.id} place={p} onClick={() => { set({ saved: { ...saved, [editing]: p } }); setEditing(null) }} />)}</div></> : <><p className="section-kicker">ВАШИ АДРЕСА</p><button className="saved-row" onClick={() => setEditing('home')}><span className="saved-icon"><Home size={22} /></span><span><strong>Дом</strong><small>{saved.home?.address ?? 'Добавить адрес'}</small></span>{saved.home ? <ChevronRight size={19} /> : <Plus size={19} />}</button><button className="saved-row" onClick={() => setEditing('work')}><span className="saved-icon"><BriefcaseBusiness size={22} /></span><span><strong>Работа</strong><small>{saved.work?.address ?? 'Добавить адрес'}</small></span>{saved.work ? <ChevronRight size={19} /> : <Plus size={19} />}</button><p className="demo-note">Нажмите на место, чтобы добавить или изменить его адрес.</p></>}</div></div>
}

function SettingsScreen({ onBack, go }: { onBack: () => void; go: (s: Overlay) => void }) {
  const { dark, language, notificationsEnabled, set, resetApp } = useTaxiStore()
  return <div className="full-screen"><PageHeader title="Настройки" onBack={onBack} /><div className="screen-content"><p className="section-kicker">ПРЕДПОЧТЕНИЯ</p><button className="menu-row" onClick={() => go('language')}><span>Язык</span><small>{language}</small><ChevronRight size={18} /></button><button className="menu-row" onClick={() => set({ dark: !dark })}><span>Тёмная тема</span><span className={`switch ${dark ? 'on' : ''}`}><i /></span></button><button className="menu-row" onClick={() => set({ notificationsEnabled: !notificationsEnabled })}><span>Уведомления</span><span className={`switch ${notificationsEnabled ? 'on' : ''}`}><i /></span></button><p className="section-kicker settings-heading">ДОПОЛНИТЕЛЬНО</p><button className="menu-row" onClick={() => go('about')}><span>Конфиденциальность</span><ChevronRight size={18} /></button><button className="menu-row" onClick={() => go('about')}><span>Геолокация</span><ChevronRight size={18} /></button><button className="menu-row" onClick={() => go('about')}><span>О приложении</span><ChevronRight size={18} /></button><button className="menu-row logout" onClick={() => { set({ user: null, tab: 'home', stage: 'idle' }); onBack() }}><span>Выйти из аккаунта</span><ArrowRight size={18} /></button><button className="dev-entry" onClick={() => go('developer')} aria-label="Открыть панель разработчика"><Settings2 size={16} /> Demo tools</button><button className="reset-link" onClick={() => { if (window.confirm('Сбросить все данные демо-приложения?')) { resetApp(); onBack() } }}>Сбросить приложение</button></div></div>
}

function DeveloperPanel({ onBack, onJump, toast }: { onBack: () => void; onJump: () => void; toast: (s: string) => void }) {
  const { set, resetApp, simulateNoDrivers, simulatePaymentError } = useTaxiStore()
  const driver = drivers[0]
  const prep = (stage: RideStage) => { set({ tab: 'home', stage, pickup: places[0], destination: places[2], driver, tripId: `demo-${Date.now()}`, progress: 0, eta: 3 }); onJump() }
  return <div className="full-screen"><PageHeader title="Demo tools" onBack={onBack} /><div className="screen-content"><p className="demo-note">Только для тестирования сценариев приложения.</p><p className="section-kicker">ПЕРЕЙТИ К СОСТОЯНИЮ</p>{[['Водитель найден','driverFound'],['Водитель прибыл','driverArrived'],['Начать поездку','inProgress'],['Завершить поездку','rideCompleted']].map(([label, stage]) => <button key={stage} className="menu-row" onClick={() => prep(stage as RideStage)}><span>{label}</span><ChevronRight size={18} /></button>)}<p className="section-kicker settings-heading">СИМУЛЯЦИЯ ОШИБОК</p><button className="menu-row" onClick={() => { set({ simulateNoDrivers: !simulateNoDrivers }); toast(`Нет водителей: ${!simulateNoDrivers ? 'включено' : 'выключено'}`) }}><span>Нет водителей</span><span className={`switch ${simulateNoDrivers ? 'on' : ''}`}><i /></span></button><button className="menu-row" onClick={() => { set({ simulatePaymentError: !simulatePaymentError }); toast(`Ошибка оплаты: ${!simulatePaymentError ? 'включено' : 'выключено'}`) }}><span>Ошибка оплаты</span><span className={`switch ${simulatePaymentError ? 'on' : ''}`}><i /></span></button><button className="menu-row logout" onClick={() => { if (window.confirm('Удалить локальные данные Voya?')) { resetApp(); onBack() } }}><span>Очистить localStorage</span><ChevronRight size={18} /></button></div></div>
}

export default function App() {
  const store = useTaxiStore()
  const reduceMotion = useReducedMotion()
  const [splash, setSplash] = useState(true)
  const [overlay, setOverlay] = useState<Overlay>('none')
  const [detail, setDetail] = useState<Trip | null>(null)
  const [toast, setToast] = useState<string | null>(null)
  const showToast = (message: string) => { setToast(message); window.setTimeout(() => setToast(null), 2900) }
  useEffect(() => { const t = setTimeout(() => setSplash(false), 1100); return () => clearTimeout(t) }, [])
  useEffect(() => { document.documentElement.classList.toggle('dark', store.dark) }, [store.dark])
  useEffect(() => registerTaxiTools(), [])
  useEffect(() => { if (store.stage !== 'searchingDriver') return; let alive = true; mockTaxiApi.findDriver(store.simulateNoDrivers).then(driver => { if (!alive) return; store.set({ driver, stage: 'driverFound', notices: [{ id: `found-${Date.now()}`, title: 'Водитель найден', body: `${driver.name} будет через 3 минуты.`, time: 'Сейчас', unread: true, type: 'ride' }, ...useTaxiStore.getState().notices] }) }).catch(() => { if (alive) store.set({ stage: 'searchError', simulateNoDrivers: false }) }); return () => { alive = false } }, [store.stage, store.simulateNoDrivers])
  useEffect(() => { if (store.stage !== 'driverFound') return; const t = setTimeout(() => store.set({ stage: 'driverApproaching', progress: 0 }), 1600); return () => clearTimeout(t) }, [store.stage])
  useEffect(() => { if (store.stage !== 'driverApproaching') return; const t = setInterval(() => { const s = useTaxiStore.getState(); const next = Math.min(1, s.progress + .083); s.set({ progress: next, eta: Math.max(1, Math.ceil((1 - next) * 3)), stage: next >= 1 ? 'driverArrived' : 'driverApproaching' }) }, 1000); return () => clearInterval(t) }, [store.stage])
  useEffect(() => { if (store.stage !== 'inProgress') return; const t = setInterval(() => { const s = useTaxiStore.getState(); const next = Math.min(1, s.progress + .05); s.set({ progress: next }); if (next >= 1) { clearInterval(t); mockTaxiApi.completeRide().then(() => useTaxiStore.getState().set({ stage: 'rideCompleted' })) } }, 1000); return () => clearInterval(t) }, [store.stage])
  useEffect(() => { if (store.stage !== 'processingPayment') return; let alive = true; mockTaxiApi.processPayment(store.payment, store.simulatePaymentError).then(() => { if (alive) useTaxiStore.getState().set({ stage: 'paymentSuccess' }) }).catch(() => { if (alive) store.set({ stage: 'paymentError', simulatePaymentError: false }) }); return () => { alive = false } }, [store.stage, store.payment, store.simulatePaymentError])
  useEffect(() => { if (store.stage !== 'paymentSuccess') return; const t = setTimeout(() => store.set({ stage: 'rating' }), 1450); return () => clearTimeout(t) }, [store.stage])
  const open = (next: Overlay) => { setOverlay(next) }
  const back = () => { if (overlay === 'card') setOverlay('payment'); else setOverlay('none') }
  const pickDestination = async (place: Place) => { setOverlay('none'); store.set({ stage: 'routePreview', destination: place }); await mockTaxiApi.calculateRoute(store.pickup, place) }
  const pickPickup = (place: Place) => { store.set({ pickup: place, stage: store.destination ? 'routePreview' : 'idle' }); setOverlay('none') }
  const repeat = () => { if (!detail) return; store.set({ tab: 'home', pickup: detail.pickup, destination: detail.destination, stage: 'routePreview' }); setOverlay('none') }
  const stageActive = !['idle','cancelled','selectingPickup','selectingDestination'].includes(store.stage)
  const showTabBar = !stageActive && overlay === 'none'
  return <MotionConfig reducedMotion="user"><div className="desktop-stage"><div className="app-shell"><AnimatePresence mode="wait">
    {splash ? <motion.div key="splash" className="splash-screen" exit={{ opacity: 0, filter: 'blur(9px)' }} transition={{ duration: .4 }}><motion.div initial={{ opacity: 0, scale: .78, filter: 'blur(9px)' }} animate={{ opacity: 1, scale: 1, filter: 'blur(0px)' }} transition={{ type: 'spring', stiffness: 320, damping: 28 }}><Logo light /></motion.div><span>БАКУ В ВАШЕМ РИТМЕ</span></motion.div> : !store.onboardingDone ? <motion.div key="onboarding" className="app-page" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><Onboarding onDone={() => store.set({ onboardingDone: true })} /></motion.div> : !store.user ? <motion.div key="auth" className="app-page" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><Auth onComplete={() => store.set({ tab: 'home' })} /></motion.div> : <motion.div key="main" className="app-page" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
      <AnimatePresence mode="wait">{store.tab === 'home' ? <motion.div key="home" className="home-screen" initial={{ opacity: 0, x: reduceMotion ? 0 : 10 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: reduceMotion ? 0 : -10 }} transition={{ duration: .23 }}><TaxiMap /><div className="home-top"><button className="home-profile" onClick={() => store.set({ tab: 'profile' })}><Avatar initials={`${store.user?.firstName[0]}${store.user?.lastName[0]}`.toUpperCase()} /><span>Привет, {store.user?.firstName}</span></button><button className="locate-button" onClick={() => showToast('Вы находитесь рядом с Nizami Street')} aria-label="Моё местоположение"><LocateFixed size={21} /></button></div><HomeSheet openSearch={() => open('search')} openPickup={() => open('pickup')} openPayment={() => open('payment')} toast={showToast} setToast={showToast} /></motion.div> : store.tab === 'trips' ? <motion.div key="trips" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }}><TripsScreen onOpen={t => { setDetail(t); open('detail') }} /></motion.div> : store.tab === 'notifications' ? <motion.div key="notices" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }}><NotificationsScreen /></motion.div> : <motion.div key="profile" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }}><ProfileScreen go={open} toast={showToast} /></motion.div>}</AnimatePresence>
      {showTabBar && <TabBar active={store.tab} onChange={tab => store.set({ tab })} unread={store.notices.some(n => n.unread)} />}
      <AnimatePresence mode="wait">{overlay !== 'none' && <motion.div key={overlay} className="overlay-wrap" initial={{ x: reduceMotion ? 0 : '100%', opacity: 0 }} animate={{ x: 0, opacity: 1 }} exit={{ x: reduceMotion ? 0 : '100%', opacity: 0 }} transition={spring}>{overlay === 'search' && <SearchScreen mode="destination" onBack={back} onSelect={pickDestination} />}{overlay === 'pickup' && <SearchScreen mode="pickup" onBack={back} onSelect={pickPickup} />}{overlay === 'payment' && <PaymentScreen onBack={back} onCard={() => open('card')} />}{overlay === 'card' && <CardScreen onBack={() => setOverlay('payment')} />}{overlay === 'saved' && <SavedPlaces onBack={back} />}{overlay === 'settings' && <SettingsScreen onBack={back} go={open} />}{overlay === 'developer' && <DeveloperPanel onBack={() => setOverlay('settings')} onJump={() => setOverlay('none')} toast={showToast} />}{overlay === 'detail' && detail && <TripDetail trip={detail} onBack={back} onRepeat={repeat} />}{overlay === 'personal' && <div className="full-screen"><PageHeader title="Личные данные" onBack={back} /><div className="screen-content"><div className="personal-avatar"><Avatar initials={`${store.user.firstName[0]}${store.user.lastName[0]}`} large /></div><div className="detail-section"><div className="detail-line"><span>Имя</span><strong>{store.user.firstName}</strong></div><div className="detail-line"><span>Фамилия</span><strong>{store.user.lastName}</strong></div><div className="detail-line"><span>Телефон</span><strong>{store.user.phone}</strong></div><div className="detail-line"><span>Email</span><strong>{store.user.email || 'Не указан'}</strong></div></div><p className="demo-note">Данные тестового профиля сохранены только на этом устройстве.</p></div></div>}{overlay === 'language' && <div className="full-screen"><PageHeader title="Язык" onBack={() => setOverlay('settings')} /><div className="screen-content">{['Русский','English','Azərbaycan dili'].map(lang => <button className="menu-row" key={lang} onClick={() => { store.set({ language: lang }); setOverlay('settings'); if (lang !== 'Русский') showToast('Полный перевод появится позже') }}><span>{lang}</span>{store.language === lang && <Check size={20} />}</button>)}</div></div>}{overlay === 'about' && <div className="full-screen"><PageHeader title="О приложении" onBack={() => setOverlay('settings')} /><div className="screen-content about-screen"><Logo /><h2>Поездки по Баку</h2><p>Voya — демонстрационная версия будущего мобильного сервиса. Маршруты, водители, оплата и геолокация здесь имитируются для тестирования интерфейса.</p><div className="detail-line"><span>Версия</span><strong>1.0 Demo</strong></div><div className="detail-line"><span>Данные</span><strong>Только на устройстве</strong></div></div></div>}</motion.div>}</AnimatePresence>
      <Toast message={toast} />
    </motion.div>}
  </AnimatePresence></div><div className="desktop-caption"><Logo /><span>Интерактивная демоверсия для мобильного экрана</span></div></div></MotionConfig>
}
